---
- name: nfs client configuration
  hosts: all
  tasks:
    - name: making directory
      file:
        path: /nfs2-share
        state: directory
    - name: make boot persistent
      mount:
        path: /nfs2-share
        src: 192.168.100.102:/nas4
        fstype: nfs
        state: mounted

