---
- name: Setup passwordless SSH login
  hosts: all
  become: yes
  vars:
    ssh_user: root
    pubkey: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/root/.ssh"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0700'

    - name: Copy public key to authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        key: "{{ pubkey }}"
        state: present
