---
- name: Change SSH port
  hosts: all
  become: yes

  vars:
    new_ssh_port: 22

  tasks:
    - name: Update sshd_config with new port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: "Port {{ new_ssh_port }}"
        backup: yes

    - name: Allow new SSH port in firewall (firewalld)
      firewalld:
        port: "{{ new_ssh_port }}/tcp"
        permanent: yes
        state: enabled
      when: ansible_os_family == "RedHat"

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
